# Generated by Django 3.1.4 on 2021-01-26 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='usn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
