# Generated by Django 3.1.4 on 2021-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210126_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='usn',
            field=models.CharField(default='', max_length=50),
        ),
    ]
