# Generated by Django 3.1.4 on 2021-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210126_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
