# Generated by Django 3.1.4 on 2021-01-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210126_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id',
            new_name='studId',
        ),
    ]
