# Generated by Django 3.1.4 on 2021-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210126_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='studId',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
